default_language_version:
  python: python3
default_stages: [commit]
exclude: ^imageProcessing/
fail_fast: true

repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --skip imageProcessing/
        language: python
        types: [python]

      - id: black
        name: black
        entry: black --extend-exclude 'imageProcessing/'
        language: python
        types: [python]

      - id: flake8
        name: flake8
        entry: flake8 --exclude imageProcessing/
        language: python
        types: [python]

      - id: mypy
        name: mypy
        entry: mypy .
        language: python
        types: [python]
        pass_filenames: false

      # - id: pytest
      #   name: pytest
      #   entry: pytest tests
      #   language: python
      #   types: [python]
      #   pass_filenames: false
